export const FETCH_TYPE_POST_URL = 'RUL';
export const FETCH_TYPE_POST_BODY = 'BODY';
export const FETCH_TYPE_POST_URL2PARAMS = 'RUL2PARAMS';
export const FETCH_TYPE_POST_URL2BODY = 'URL2BODY';

export const FETCH_TYPE_GET_URL = 'RUL';
export const FETCH_TYPE_GET_URL2PARAMS = 'RUL2PARAMS';

